language: rust
cache: cargo

os:
- linux
- osx

rust:
- nightly
- beta
- stable

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev

before_script:
- pip install -v 'travis-cargo<0.2' --user
- if [[ -e ~/.local/bin ]]; then export PATH=~/.local/bin:$PATH; fi

script:
- |
  cargo build &&
  cargo test &&
  cargo bench

after_success:
- if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "nightly" ]]; then travis-cargo coveralls --no-sudo --verify; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "nightly" ]]; then KCOV=./kcov/build/src/kcov ./coverage; fi

env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly
