language: rust
cache: cargo
sudo: false

addons:
  apt:
    packages:
    - binutils

before_script:
- export RUST_BACKTRACE=1

script: ./ci/script.sh

os:
- linux
- osx

rust:
- nightly
- beta
- stable

env:
- GIMLI_JOB="build"
- GIMLI_JOB="features"

matrix:
  fast_finish: true
  include:
    # Coverage should only run on Linux and stable Rust.
    - rust: stable
      os: linux
      sudo: required
      env: GIMLI_JOB="coverage"
    # Building docs only needs to happen on one os and only on stable.
    - rust: stable
      os: linux
      env: GIMLI_JOB="doc"
    # Benching should only happen on nightly.
    - rust: nightly
      env: GIMLI_JOB="bench"
    # Some features require nightly.
    - rust: nightly
      env: GIMLI_JOB="nightly_features"
