language: rust
cache: cargo

# use a more up-to-date Travis environment
dist: trusty
sudo: false

os:
- linux
- osx

rust:
- nightly
- beta
- stable

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev

before_script:
- pip install -v 'travis-cargo<0.2' --user
- if [[ -e ~/Library/Python/2.7/bin ]]; then export PATH=~/Library/Python/2.7/bin:$PATH; fi
- if [[ -e ~/.local/bin ]]; then export PATH=~/.local/bin:$PATH; fi

script:
-  travis-cargo build -- --no-default-features
-  travis-cargo build -- --no-default-features --features "cpp_demangle"
-  travis-cargo build -- --no-default-features --features "rustc-demangle"
-  travis-cargo build
-  if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then travis-cargo test; fi
-  travis-cargo bench

after_success:
- if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "nightly" ]]; then travis-cargo coveralls --no-sudo --verify; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "nightly" ]]; then KCOV=./kcov/build/src/kcov ./coverage; fi

env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly
