[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
name = "addr2line"
version = "0.1.0"

[dependencies]
fallible-iterator = "0.1.3"
getopts = "0.2.14"
gimli = "0.9.0"
memmap = "0.5.0"
object = "0.1.0"
