[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
description = "A cross-platform `addr2line` clone written in Rust, using `gimli`"
documentation = "https://docs.rs/addr2line"
keywords = ["DWARF", "debug", "elf", "symbolicate", "atos"]
categories = ["development-tools::debugging", "command-line-utilities"]
license = "Apache-2.0/MIT"
name = "addr2line"
readme = "./README.md"
repository = "https://github.com/gimli-rs/addr2line"
version = "0.2.1"
build = "build.rs"

[badges]
travis-ci = { repository = "gimli-rs/addr2line" }

[dependencies]
fallible-iterator = "0.1.3"
clap = "2.19.1"
gimli = "0.11.0"
memmap = "0.5.0"
object = "0.1.0"
owning_ref = "0.2.4"
error-chain = "0.7.1"
rustc-demangle = "0.1.3"

[dev-dependencies]
glob = "0.2"
itertools = "0.5"

[features]
nightly = []
