[package]
name = "unwind"
version = "0.1.0"
authors = ["main() <main@ehvag.de>"]

[dependencies]
gimli = { path = "../dbgc/gimli" }
libc = "0.2"
fallible-iterator = "0.1"

[build-dependencies]
gcc = "0.3"

[dev-dependencies]
backtrace = "0.3"
