[package]
name = "hardliner"
version = "0.1.0"
authors = ["main() <main@ehvag.de>"]

[profile.release]
debug = true

[dependencies]
gimli = { path = "../gimli" }
fallible-iterator = "0.1"
object = "0.4"
intervaltree = "0.2"
smallvec = "0.4"
rustc-demangle = { version = "0.1", optional = true }
cpp_demangle = { version = "0.2", optional = true }

[dev-dependencies]
memmap = "0.5"
clap = "2"
backtrace = "0.3"
findshlibs = "0.3"

[features]
default = ["rustc-demangle", "cpp_demangle"]
