[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
description = "A cross-platform `addr2line` clone written in Rust, using `gimli`"
documentation = "https://docs.rs/addr2line"
keywords = ["DWARF", "debug", "elf", "symbolicate", "atos"]
license = "Apache-2.0/MIT"
name = "addr2line"
readme = "./README.md"
repository = "https://github.com/gimli-rs/addr2line"
version = "0.2.0"
build = "build.rs"

[dependencies]
fallible-iterator = "0.1.3"
clap = "2.19.1"
gimli = { git = "https://github.com/gimli-rs/gimli.git" } # need entries_at_offset
memmap = "0.5.0"
object = "0.1.0"
owning_ref = { git = "https://github.com/Kimundi/owning-ref-rs" } # need OwningHandle

[dev-dependencies]
glob = "0.2"
itertools = "0.5"

[features]
nightly = []
